### ISSUE TITLE
chart should have a default height

### ISSUE THREAD

**Issue by mrbedo** [Polymoar/d3-line-chart#1]
The default example doesn't show anything unless a style is specified with a min-height.

Other than that, very easy and great job!

**Comment by Junikorn** [comment]
Hi, not sure what you have in mind because this is one of my original assumptions and it's mentioned on the component page ("you need to set chart's dimensions (at least min width/height) or put it into layout for it to display"). I've made this decision because I did not wanted to force way of chart display on anyone and this solution allows you to match chart display to your needs with a few lines of css. If I did not understand your thought please clarify.

As for demo page for me it works on all browsers I tested (evergreens / Safari). Style for chart element with min-height is embed in the demo.html source so it should always load.

**Comment by mrbedo** [comment]
The chart element should have some reasonable default values. Height of 0 is not very reasonable for a default value.  Since no height is specified, if the simplest chart code is pasted in, nothing appears and is confusing. It makes it seem like the element doesn't function properly.  Unless you debug it, or re-read the requirements that a height is required.

Perhaps as a more simple solution, the minimal sample code include a height style. :)

**Comment by Junikorn** [comment]
Well I agree, actually reasonable default value of height wouldn't hurt as it will be very easy to overwrite. Default height is now 400px. Thanks for your feedback :)
Fix: https://github.com/Polymoar/d3-line-chart/commit/618f33beb792b79fba0a0a566f7f33b39accf985
